"use client";

import { Metadata } from 'next';
import Image from 'next/image'

const styles = {
  main:
    "flex justify-center items-center min-h-screen text-white h-screen",
  content: {
    base: "grid gap-10 grid-cols-1 md:grid-cols-2 md:divide-x md:divide-gray-600 text-white h-96",
    info: "flex flex-col gap-20 align-right items-end justify-center",
    form: "flex flex-col gap-5 justify-center pl-10"
  },
  text: {
    textInfo: "text-4xl font-bold flex flex-col text-right",
    colorGreen: "text-green-secondary mt-3",
  },
  icon: "text-base"
}

export const metadata: Metadata = {
  title: 'XGrow Frontend',
  description: 'Generated by create next app',
}

export default function LoginLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main className={styles.main}>
        <div className={styles.content.base}>
            <div className={styles.content.info}>
            <Image
                src="/images/logo-xgrow.png"
                alt="XGROW"
                width={212}
                height={53}
            />
            <div className={styles.text.textInfo}>
                <span>
                Seja bem vindo à
                </span>
                <span className={styles.text.colorGreen}>
                Área do aluno
                </span>
            </div>
            </div>
            <div className={styles.content.form}>
                {children}
            </div>
        </div>
        </main>
      </body>
    </html>
  )
}
