import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import { AuthProvider } from '@/contexts/AuthContext'

const poppins = Poppins({
  subsets: ['latin'],
  weight: '500'
})
export const metadata: Metadata = {
  title: 'XGrow Frontend',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <AuthProvider>
      <html lang="pt-BR" className={poppins.className}>
        <body>
          {children}
        </body>
      </html>
    </AuthProvider>
  )
}
